Explicitly list fs files in fsprojs.
F# SDK style projects must explicitly list the .fs files, because the order matters.

Reference: https://xamarinhq.slack.com/archives/C0VFPK631/p1553850714002700

Fixes compiler errors like these:

    "xamarin-forms-book-samples/Chapter03/FS/Baskervilles/Baskervilles/Baskervilles.iOS/Baskervilles.iOS.csproj" (default target) (1) ->
    (CoreCompile target) ->
      AppDelegate.cs(26,33): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [xamarin-forms-book-samples/Chapter03/FS/Baskervilles/Baskervilles/Baskervilles.iOS/Baskervilles.iOS.csproj]